name: Auto Grade

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect project files
        id: detect
        run: |
          echo "has_pkg=$( [ -f package.json ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "has_lock=$( [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "has_grader=$( [ -f scripts/grader.js ] && echo true || echo false )" >> $GITHUB_OUTPUT

      - name: Install deps (if package.json exists)
        if: steps.detect.outputs.has_pkg == 'true'
        run: |
          if [ "${{ steps.detect.outputs.has_lock }}" = "true" ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Run grader (if grader exists)
        if: steps.detect.outputs.has_grader == 'true'
        env:
          # Arabia Standard Time is +03:00
          DUE_DATE: "2025-10-01T23:59:59+03:00"
        run: npm run grade

      - name: Upload grade artifact (JSON + Markdown) if present
        if: ${{ hashFiles('grading/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: grade-report
          path: grading/

      - name: Publish Grade Summary
        if: always()
        run: |
          echo "## Auto Grade Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f grading/grade.md ]; then
            cat grading/grade.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No grading output produced." >> $GITHUB_STEP_SUMMARY
            echo "- Ensure package.json and scripts/grader.js exist." >> $GITHUB_STEP_SUMMARY
            echo "- Push another commit or run this workflow manually." >> $GITHUB_STEP_SUMMARY
