name: Auto Grade

on:
  push:
  pull_request:
  workflow_dispatch:

# All run steps execute inside the subfolder where package.json lives
defaults:
  run:
    working-directory: 5-2-react-starter

env:
  # Riyadh timezone (+03:00)
  DUE_DATE: "2025-10-01T23:59:59+03:00"

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect project files (in subfolder)
        id: detect
        shell: bash
        run: |
          echo "has_pkg=$( [ -f package.json ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "has_lock=$( [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ] && echo true || echo false )" >> $GITHUB_OUTPUT
          if [ -f scripts/grader.cjs ]; then
            echo "has_grader=true" >> $GITHUB_OUTPUT
            echo "grader_path=scripts/grader.cjs" >> $GITHUB_OUTPUT
          elif [ -f scripts/grader.js ]; then
            echo "has_grader=true" >> $GITHUB_OUTPUT
            echo "grader_path=scripts/grader.js" >> $GITHUB_OUTPUT
          else
            echo "has_grader=false" >> $GITHUB_OUTPUT
            echo "grader_path=" >> $GITHUB_OUTPUT
          fi

      - name: Print detection
        shell: bash
        run: |
          echo "has_pkg=${{ steps.detect.outputs.has_pkg }}"
          echo "has_lock=${{ steps.detect.outputs.has_lock }}"
          echo "has_grader=${{ steps.detect.outputs.has_grader }}"
          echo "grader_path=${{ steps.detect.outputs.grader_path }}"

      - name: Install deps (if package.json exists)
        if: steps.detect.outputs.has_pkg == 'true'
        run: |
          if [ "${{ steps.detect.outputs.has_lock }}" = "true" ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Run grader (node direct, if grader exists)
        if: steps.detect.outputs.has_grader == 'true'
        run: node "${{ steps.detect.outputs.grader_path }}"

      - name: Upload grade artifact (JSON + Markdown) if present
        # hashFiles evaluates from the repo root, so include the subfolder path
        if: ${{ hashFiles('5-2-react-starter/grading/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: grade-report
          path: ${{ github.workspace }}/5-2-react-starter/grading/

      - name: Publish Grade Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Auto Grade Report"
            echo
            if [ -f grading/grade.md ]; then
              # defaults.run puts us in 5-2-react-starter, so this path is correct
              cat grading/grade.md
            else
              echo "No grading output produced."
              echo "- Detected has_pkg=${{ steps.detect.outputs.has_pkg }}, has_grader=${{ steps.detect.outputs.has_grader }}, grader_path='${{ steps.detect.outputs.grader_path }}'."
              echo "- Ensure the grader file exists and prints a report."
            fi
          } >> "$GITHUB_STEP_SUMMARY"
