name: Auto Grade

on:
  push:
  pull_request:
  workflow_dispatch:

# All run steps execute inside the subfolder
defaults:
  run:
    working-directory: 5-2-react-starter

env:
  # Set your due date (Riyadh +03:00)
  DUE_DATE: "2025-10-01T23:59:59+03:00"
  SUBDIR: 5-2-react-starter

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect project files (in subfolder)
        id: detect
        run: |
          echo "has_pkg=$( [ -f package.json ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "has_lock=$( [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "has_grader=$( [ -f scripts/grader.js ] && echo true || echo false )" >> $GITHUB_OUTPUT

      - name: Install deps (if package.json exists)
        if: steps.detect.outputs.has_pkg == 'true'
        run: |
          if [ "${{ steps.detect.outputs.has_lock }}" = "true" ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Run grader (if grader exists)
        if: steps.detect.outputs.has_grader == 'true'
        run: npm run grade

      - name: Upload grade artifact (JSON + Markdown) if present
        # hashFiles evaluates from repo root, so use the subdir path
        if: ${{ hashFiles('5-2-react-starter/grading/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: grade-report
          path: ${{ github.workspace }}/5-2-react-starter/grading/

      - name: Publish Grade Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Auto Grade Report"
            echo
            if [ -f grading/grade.md ]; then
              # defaults.run puts us in subfolder, so grading/grade.md is local
              cat grading/grade.md
            else
              echo "No grading output produced."
              echo "- Ensure package.json and scripts/grader.js exist in $SUBDIR."
              echo "- Verify the npm script: \"grade\": \"node scripts/grader.js\"."
              echo "- Push another commit or Run workflow manually."
            fi
          } >> "$GITHUB_STEP_SUMMARY"
